[package]
name = "abc"
version = "0.2.0"
edition = "2024"
rust-version = "1.93"

[dependencies]
esp-idf-svc = { version = "0.52" }
log = "0.4"

# --- Optional Embassy Integration ---
# esp-idf-svc = { version = "0.52", features = ["native", "embassy-time-driver", "alloc"] }

# a) Standalone Embassy libs ( embassy-time, embassy-sync etc.) with a foreign async runtime:
# embassy-time = { version = "0.5", features = ["log", "generic-queue-8"] } # NOTE: any generic-queue variant will work

# b) With embassy-executor:
# embassy-executor = { version = "0.10", features = ["executor-thread", "platform-std"] }

# NOTE!!! This comment was edited 11-Jun-26, NOT TRYING THINGS OUT. PLEASE CHECK THE COMMIT BEFORE IF YOU NEED TO USE
#       the more exotic combinations!  Sorry for the mess.

# NOTE: if you use embassy-time with embassy-executor you don't need the generic-queue-8 feature

[build-dependencies]
embuild = "0.33"

[features]
default = []

[[bin]]
name = "abc"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

#r [profile.dev]
#r debug = true    # Symbols are nice, and they don't increase the size on Flash
#r opt-level = "z"

# Needed for https://github.com/esp-rs/embuild/issues/105 (using ESP-IDF 6.0.1)
[patch.crates-io]
embuild = { git = "https://github.com/esp-rs/embuild" }
# > 0.37.2: https://github.com/esp-rs/esp-idf-sys/commit/b0990892a63d808af25c7bda70f2726e76543743
esp-idf-sys = { git = "https://github.com/esp-rs/esp-idf-sys" }
# > 0.46.2: https://github.com/esp-rs/esp-idf-hal/commit/95adcb9ad82288b20ef032e86e2dc9de824f45e3
esp-idf-hal = { git = "https://github.com/esp-rs/esp-idf-hal" }
# > 0.52.1: https://github.com/esp-rs/esp-idf-svc/commit/e1761de00f0ac905da0ce592767184f8c851d5e0
esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf-svc" }
