[package]
name = "abc"
version = "0.2.0"
edition = "2024"
rust-version = "1.89"

[dependencies]
esp-idf-svc = { version = "0.52" }
log = "0.4"

# --- Optional Embassy Integration ---
# esp-idf-svc = { version = "0.52", features = ["native", "embassy-time-driver", "alloc"] }

# a) Standalone Embassy libs ( embassy-time, embassy-sync etc.) with a foreign async runtime:
# embassy-time = { version = "0.5", features = ["log", "generic-queue-8"] } # NOTE: any generic-queue variant will work

# b) With embassy-executor:
# embassy-executor = { version = "0.10", features = ["executor-thread", "platform-std"] }

# NOTE!!! This comment was edited 11-Jun-26, NOT TRYING THINGS OUT. PLEASE CHECK THE COMMIT BEFORE IF YOU NEED TO USE
#       the more exotic combinations!  Sorry for the mess.

# NOTE: if you use embassy-time with embassy-executor you don't need the generic-queue-8 feature

[build-dependencies]
embuild = "0.33"

[features]
default = []

[[bin]]
name = "abc"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

#r [profile.dev]
#r debug = true    # Symbols are nice, and they don't increase the size on Flash
#r opt-level = "z"

# Needed for https://github.com/esp-rs/embuild/issues/105 (using ESP-IDF 6.0.1)
[patch.crates-io]
embuild = { git = "https://github.com/esp-rs/embuild" }
